<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PetEcommerce.Core\PetEcommerce.Core.csproj" />
    <ProjectReference Include="..\PetEcommerce.Domain\PetEcommerce.Domain.csproj" />
    <ProjectReference Include="..\PetEcommerce.Infrastrcure\PetEcommerce.Infrastrcure.csproj" />
    <ProjectReference Include="..\PetEcommerce.Service\PetEcommerce.Service.csproj" />
  </ItemGroup>

</Project>
